# Generated by Django 2.0 on 2022-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Mobile_Number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
