# Generated by Django 2.0 on 2022-06-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0002_auto_20220614_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='City',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='State',
        ),
    ]
