# Generated by Django 2.0 on 2022-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0003_auto_20220615_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
