# Generated by Django 2.0 on 2022-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0004_user_data_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Uploaded_files',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
