# Generated by Django 2.0 on 2022-06-15 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_D', '0005_user_data_uploaded_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploads', models.FileField(blank=True, null=True, upload_to='uploaded_files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='Uploaded_files',
        ),
    ]
