# Generated by Django 2.0 on 2022-06-15 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0006_auto_20220615_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
