# Generated by Django 2.0 on 2022-06-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0007_auto_20220615_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Profile_pic',
            field=models.ImageField(blank=True, default='static/profile-default.png', null=True, upload_to='profile_pic/'),
        ),
    ]
