# Generated by Django 2.0 on 2022-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0009_auto_20220616_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Profile_pic',
            field=models.ImageField(default='media/static/profile-default.png', upload_to='profile_pic/'),
        ),
    ]
