# Generated by Django 2.0 on 2022-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0013_auto_20220617_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='file_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
