# Generated by Django 2.0 on 2022-06-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0017_uploaded_files_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='Age',
        ),
    ]
