# Generated by Django 2.0 on 2022-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0018_remove_user_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='Type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
