# Generated by Django 2.0 on 2022-06-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0019_uploaded_files_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='file_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
