# Generated by Django 2.0 on 2022-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0021_auto_20220619_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='Type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
