# Generated by Django 2.0 on 2022-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0024_auto_20220619_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='Default_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
