# Generated by Django 2.0 on 2022-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0026_auto_20220620_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='Default_img',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
