# Generated by Django 2.0 on 2022-06-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0028_uploaded_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User_D.Uploaded_folder'),
        ),
    ]
