# Generated by Django 2.0 on 2022-06-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0029_uploaded_files_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30, null=True)),
                ('file_size_kb', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
