# Generated by Django 2.0 on 2022-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0030_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_folder',
            name='Parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
