# Generated by Django 2.0 on 2022-06-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_D', '0032_auto_20220623_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_folder',
            name='Parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
